# Generated by Django 5.2.4 on 2025-08-24 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manga', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookmark',
            name='image_url',
            field=models.URLField(blank=True, max_length=300, null=True),
        ),
    ]
