# Generated by Django 5.2.4 on 2025-07-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DataFeatcher', '0002_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='image_url',
        ),
    ]
