# Generated by Django 5.2.4 on 2025-07-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataFeatcher', '0004_banner_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('anime_id', models.IntegerField(unique=True)),
                ('image_url', models.URLField()),
                ('score', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('episodes', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
