# Generated by Django 5.2.4 on 2025-07-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataFeatcher', '0005_watchlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_thumbnail',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='anime',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
