# Generated by Django 5.2.4 on 2025-08-23 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DataFeatcher', '0007_watchlist_user_alter_watchlist_anime_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
