# Generated by Django 5.2.4 on 2025-08-24 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0002_bookmark'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookmark',
            old_name='bookmark_id',
            new_name='Manga_id',
        ),
    ]
