# Generated by Django 5.2.4 on 2025-08-24 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Main', '0006_alter_bookmark_manga_id_alter_bookmark_title'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Bookmark',
        ),
    ]
